services:
  tms-db:
    image: postgres:latest
    container_name: tms-db
    ports:
      - "5432:5432"
    volumes:
      - /home/somanwokoye/data/postgres:/data/postgres
    env_file:
      - docker.env
