services:
  tms-db:
    image: postgres:latest
    container_name: tms-db
    ports:
      - "5432:5432"
    volumes:
      - /Users/piusonobhayedo/data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
