services:
  tms-database:
    image: postgres:latest
    container_name: tms-database
    ports:
      - "5432:5432"
    volumes:
      - /home/somanwokoye/data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
